// src/constants/icons.ts
import type { HabitIconName } from "@/types/app";
import {
  // existing:
  Award,
  BarChart3,
  Bed,
  BookOpen,
  Brain,
  Calendar,
  Clock,
  Coffee,
  Droplets,
  Dumbbell,
  Flame,
  Heart,
  Smile,
  Star,
  Target,
  Trophy,
  Zap,
  // add more here as you like:
  AlarmClock,
  Apple,
  Bath,
  Battery,
  Bell,
  Bike,
  Bolt,
  Book,
  Check,
  ChevronRight,
  Cloud,
  Code,
  Cookie,
  Crown,
  Diamond,
  Eye,
  Feather,
  Footprints,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  HandHeart,
  Headphones,
  Leaf,
  Lightbulb,
  Moon,
  Music,
  PawPrint,
  Pencil,
  Phone,
  Pin,
  Plane,
  Plus,
  Rocket,
  Shield,
  Sun,
  Timer,
  Trees,
  Umbrella,
  Watch,
} from "lucide-vue-next";

// 1) One array drives everything.
export const HABIT_ICONS = [
  // --- keep your existing first so old data keeps working ---
  { label: "Часы", value: "Clock", component: Clock },
  { label: "Звезда", value: "Star", component: Star },
  { label: "Кофе", value: "Coffee", component: Coffee },
  { label: "Гантеля", value: "Dumbbell", component: Dumbbell },
  { label: "Капли", value: "Droplets", component: Droplets },
  { label: "Сердце", value: "Heart", component: Heart },
  { label: "Книга", value: "BookOpen", component: BookOpen },
  { label: "Мозг", value: "Brain", component: Brain },
  { label: "Мишень", value: "Target", component: Target },
  { label: "Календарь", value: "Calendar", component: Calendar },
  { label: "Диаграмма", value: "BarChart3", component: BarChart3 },
  { label: "Кровать", value: "Bed", component: Bed },
  { label: "Кубок", value: "Trophy", component: Trophy },
  { label: "Пламя", value: "Flame", component: Flame },
  { label: "Улыбка", value: "Smile", component: Smile },
  { label: "Награда", value: "Award", component: Award },
  { label: "Молния", value: "Zap", component: Zap },

  // --- add as many as you want below ---
  { label: "Будильник", value: "AlarmClock", component: AlarmClock },
  { label: "Яблоко", value: "Apple", component: Apple },
  { label: "Ванна", value: "Bath", component: Bath },
  { label: "Батарея", value: "Battery", component: Battery },
  { label: "Колокол", value: "Bell", component: Bell },
  { label: "Велосипед", value: "Bike", component: Bike },
  { label: "Книга (2)", value: "Book", component: Book },
  { label: "Галочка", value: "Check", component: Check },
  { label: "Облако", value: "Cloud", component: Cloud },
  { label: "Код", value: "Code", component: Code },
  { label: "Печенье", value: "Cookie", component: Cookie },
  { label: "Корона", value: "Crown", component: Crown },
  { label: "Бриллиант", value: "Diamond", component: Diamond },
  { label: "Глаз", value: "Eye", component: Eye },
  { label: "Перо", value: "Feather", component: Feather },
  { label: "Следы", value: "Footprints", component: Footprints },
  { label: "Геймпад", value: "Gamepad2", component: Gamepad2 },
  { label: "Подарок", value: "Gift", component: Gift },
  { label: "Очки", value: "Glasses", component: Glasses },
  { label: "Глобус", value: "Globe", component: Globe },
  { label: "Сердце рук", value: "HandHeart", component: HandHeart },
  { label: "Наушники", value: "Headphones", component: Headphones },
  { label: "Лист", value: "Leaf", component: Leaf },
  { label: "Лампочка", value: "Lightbulb", component: Lightbulb },
  { label: "Луна", value: "Moon", component: Moon },
  { label: "Музыка", value: "Music", component: Music },
  { label: "Лапка", value: "PawPrint", component: PawPrint },
  { label: "Карандаш", value: "Pencil", component: Pencil },
  { label: "Телефон", value: "Phone", component: Phone },
  { label: "Пин", value: "Pin", component: Pin },
  { label: "Самолет", value: "Plane", component: Plane },
  { label: "Плюс", value: "Plus", component: Plus },
  { label: "Ракета", value: "Rocket", component: Rocket },
  { label: "Щит", value: "Shield", component: Shield },
  { label: "Солнце", value: "Sun", component: Sun },
  { label: "Таймер", value: "Timer", component: Timer },
  { label: "Деревья", value: "Trees", component: Trees },
  { label: "Зонт", value: "Umbrella", component: Umbrella },
  { label: "Часы (рук.)", value: "Watch", component: Watch },
] as const;

// 3) Registry derived from the list (for <component :is="...">)
export const habitIconRegistry: Record<HabitIconName, any> = HABIT_ICONS.reduce((acc, i) => {
  acc[i.value] = i.component;
  return acc;
}, {} as Record<HabitIconName, any>);

// 4) Options for your picker
export const availableHabitIcons = HABIT_ICONS.map(({ label, value }) => ({ label, value }));
